In [193]:
import pandas as pd 
import numpy as np
import statsmodels.api as sm

from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

from matplotlib import pyplot as plt

In [194]:
file_path = "/Users/owner/Analysis_Projects/sportsref_download_2021.csv"
file_path_two = "/Users/owner/Analysis_Projects/sportsref_download_2022.csv"

baseball_2021_df = pd.read_csv(file_path)
baseball_2022_df = pd.read_csv(file_path_two)

baseball_2021_df

,Tm,#Bat,BatAge,R/G,G,PA,AB,R,H,2B,...,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,LOB,BB+HBP
0,Arizona Diamondbacks,64,28.9,4.19,162,6144,5489,679,1297,308,...,0.692,87,2099,99,54,32,28,24,1152,591
1,Atlanta Braves,56,28.2,4.91,161,6056,5363,790,1307,269,...,0.754,98,2333,81,67,32,43,36,1072,616
2,Baltimore Orioles,62,26.7,4.07,162,5983,5420,659,1296,266,...,0.705,92,2177,105,65,14,31,12,1046,516
3,Boston Red Sox,56,28.0,5.12,162,6122,5495,829,1434,330,...,0.777,106,2467,100,61,10,42,22,1093,573
4,Chicago Cubs,69,29.1,4.35,162,5972,5306,705,1255,225,...,0.719,93,2162,133,92,40,30,17,1019,594
5,Chicago White Sox,47,28.0,4.91,162,6084,5357,796,1373,275,...,0.758,106,2262,139,78,24,39,10,1125,664
6,Cincinnati Reds,55,28.9,4.85,162,6162,5423,786,1352,295,...,0.759,95,2339,129,105,35,45,22,1110,658
7,Cleveland Indians,48,26.7,4.43,162,5907,5332,717,1269,248,...,0.710,94,2170,105,64,20,36,18,987,517
8,Colorado Rockies,45,28.1,4.59,161,6007,5374,739,1338,275,...,0.731,86,2227,98,58,48,36,24,1074,549
9,Detroit Tigers,49,28.1,4.30,162,5979,5376,697,1299,236,...,0.707,96,2146,113,44,17,50,8,1031,534
10,Houston Astros,52,28.9,5.33,162,6291,5593,863,1496,299,...,0.783,113,2486,136,64,9,54,25,1159,633
11,Kansas City Royals,48,29.3,4.23,162,5993,5427,686,1349,251,...,0.702,90,2147,100,55,31,52,8,1050,476
12,Los Angeles Angels,64,29.2,4.46,162,6016,5437,723,1331,265,...,0.717,93,2212,107,59,30,25,35,1029,523
13,Los Angeles Dodgers,61,29.2,5.12,162,6239,5445,830,1330,247,...,0.759,101,2336,96,104,32,45,36,1169,717
14,Miami Marlins,61,28.2,3.85,162,5929,5348,623,1244,226,...,0.671,81,1990,95,65,30,30,25,1042,515
15,Milwaukee Brewers,61,28.7,4.56,162,6099,5362,738,1251,255,...,0.713,92,2124,102,88,25,35,26,1113,674
16,Minnesota Twins,57,28.3,4.50,162,6078,5431,729,1311,271,...,0.738,103,2300,122,70,7,42,17,1092,595
17,New York Mets,64,28.2,3.93,162,5856,5210,636,1243,228,...,0.705,93,2035,123,94,34,23,25,1099,589
18,New York Yankees,59,29.3,4.39,162,6060,5331,711,1266,213,...,0.729,100,2169,154,63,10,34,14,1097,684
19,Oakland Athletics,50,30.1,4.59,162,6104,5395,743,1284,271,...,0.723,102,2190,99,98,17,49,17,1084,643
20,Philadelphia Phillies,55,29.1,4.53,162,6089,5366,734,1288,262,...,0.726,95,2192,103,67,47,43,37,1115,631
21,Pittsburgh Pirates,64,27.5,3.76,162,5983,5336,609,1261,240,...,0.673,82,1943,102,49,31,37,24,1128,578
22,San Diego Padres,54,28.0,4.50,162,6119,5384,729,1305,273,...,0.722,101,2160,121,61,36,46,42,1123,647
23,Seattle Mariners,63,27.0,4.30,162,6010,5355,697,1209,233,...,0.688,92,2061,92,72,9,36,8,1040,607
24,San Francisco Giants,54,30.6,4.96,162,6196,5462,804,1360,271,...,0.769,107,2404,117,64,36,30,45,1138,666
25,St. Louis Cardinals,51,28.5,4.36,162,6001,5351,706,1303,261,...,0.725,99,2202,99,86,40,44,32,1081,564
26,Tampa Bay Rays,61,27.7,5.29,162,6213,5507,857,1336,288,...,0.750,110,2362,75,72,6,41,27,1085,657
27,Texas Rangers,54,26.8,3.86,162,5943,5405,625,1254,225,...,0.670,83,2028,113,58,16,31,10,1007,491
28,Toronto Blue Jays,62,26.8,5.22,162,6070,5476,846,1455,285,...,0.797,113,2552,112,51,10,35,14,1056,547
29,Washington Nationals,60,28.7,4.47,162,6113,5385,724,1388,272,...,0.754,107,2246,158,84,38,31,43,1185,657
30,League Average,50,28.4,4.53,162,6061,5398,734,1316,262,...,0.728,97,2217,111,70,26,38,23,1087,596
31,NaN,1508,28.4,4.53,4858,181818,161941,22010,39484,7863,...,0.728,97,66521,3328,2112,766,1143,703,32601,17906

In [195]:
baseball_2022_df

,Tm,#Bat,BatAge,R/G,G,PA,AB,R,H,2B,...,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,LOB,BB+HBP
0,Arizona Diamondbacks,57,26.5,4.33,162,6027,5351,702,1232,262,...,0.689,95,2061,97,60,31,50,14,1039,591
1,Atlanta Braves,53,27.5,4.87,162,6082,5509,789,1394,298,...,0.761,111,2443,103,66,1,36,13,1030,536
2,Baltimore Orioles,58,27.0,4.16,162,6049,5429,674,1281,275,...,0.695,97,2119,95,83,12,43,10,1095,559
3,Boston Red Sox,54,28.8,4.54,162,6144,5539,735,1427,352,...,0.731,102,2268,131,63,12,50,23,1133,541
4,Chicago Cubs,64,27.9,4.06,162,6072,5425,657,1293,265,...,0.698,96,2097,130,84,19,36,16,1100,591
5,Chicago White Sox,44,29.3,4.23,162,6123,5611,686,1435,272,...,0.698,97,2172,127,73,16,35,9,1117,461
6,Cincinnati Reds,66,29.4,4.00,162,5978,5380,648,1264,235,...,0.676,83,2003,127,92,12,33,6,1020,544
7,Cleveland Guardians,50,25.9,4.31,162,6163,5558,698,1410,273,...,0.699,102,2126,115,81,22,52,36,1156,531
8,Colorado Rockies,43,29.1,4.31,162,6105,5540,698,1408,280,...,0.713,90,2203,139,61,10,40,10,1113,514
9,Detroit Tigers,53,27.9,3.44,162,5870,5378,557,1240,235,...,0.632,84,1859,108,58,10,44,8,1015,438
10,Houston Astros,45,29.3,4.55,162,6054,5409,737,1341,284,...,0.743,111,2293,118,60,9,42,18,1068,588
11,Kansas City Royals,55,27.1,3.95,162,6010,5437,640,1327,247,...,0.686,93,2064,101,48,20,44,7,1091,508
12,Los Angeles Angels,66,27.9,3.85,162,5977,5423,623,1265,219,...,0.687,94,2116,95,54,25,25,28,1050,503
13,Los Angeles Dodgers,51,29.6,5.23,162,6247,5526,847,1418,325,...,0.775,112,2441,85,56,3,53,22,1159,663
14,Miami Marlins,56,28.8,3.62,162,5949,5395,586,1241,248,...,0.658,86,1961,120,70,4,36,6,1045,506
15,Milwaukee Brewers,51,29.1,4.48,162,6122,5417,725,1271,251,...,0.724,105,2213,117,80,11,37,25,1102,657
16,Minnesota Twins,61,26.9,4.30,162,6113,5476,696,1356,269,...,0.718,107,2195,133,62,10,46,11,1126,580
17,New York Mets,61,29.7,4.77,162,6176,5489,772,1422,272,...,0.744,113,2261,122,112,20,44,25,1158,622
18,New York Yankees,54,30.2,4.98,162,6172,5422,807,1308,225,...,0.751,113,2311,121,70,14,41,36,1093,690
19,Oakland Athletics,64,28.3,3.51,162,5863,5314,568,1147,249,...,0.626,82,1837,109,59,22,33,7,969,492
20,Philadelphia Phillies,56,28.1,4.61,162,6077,5496,747,1392,255,...,0.739,107,2320,116,52,6,44,15,1075,530
21,Pittsburgh Pirates,68,26.3,3.65,162,5912,5331,591,1186,221,...,0.655,84,1939,96,54,19,32,14,1016,530
22,San Diego Padres,55,28.2,4.35,162,6175,5468,705,1317,275,...,0.700,104,2087,95,65,17,46,24,1174,639
23,Seattle Mariners,59,27.5,4.26,162,6117,5375,690,1236,229,...,0.704,106,2094,120,89,9,45,17,1129,685
24,San Francisco Giants,66,30.0,4.42,162,6117,5392,716,1261,255,...,0.705,98,2101,109,95,6,53,14,1115,666
25,St. Louis Cardinals,51,28.8,4.77,162,6165,5496,772,1386,290,...,0.745,114,2309,112,80,5,45,11,1132,617
26,Tampa Bay Rays,61,27.0,4.11,162,6008,5412,666,1294,296,...,0.686,100,2041,93,57,7,31,13,1074,557
27,Texas Rangers,55,28.0,4.36,162,6029,5478,707,1308,224,...,0.696,98,2166,82,47,10,38,12,1007,503
28,Toronto Blue Jays,51,27.1,4.78,162,6158,5555,775,1464,307,...,0.760,116,2395,136,55,8,33,13,1111,555
29,Washington Nationals,55,28.7,3.72,162,5998,5434,603,1351,252,...,0.688,99,2051,141,60,20,37,12,1099,502
30,League Average,50,28.2,4.28,162,6068,5449,694,1322,265,...,0.706,100,2152,113,68,13,41,16,1087,563
31,NaN,1495,28.2,4.28,4860,182052,163465,20817,39675,7940,...,0.706,100,64546,3393,2046,390,1224,475,32611,16899

# Here are Linear and Logistic Regressions for 2021 Baseball Total Runs

In [196]:
# Here, we will do linear regrerssion for perdicted runs for the seasons in 20201 and 2022
# The regression coefficients are 
# 
# First, here is 2021. 

runs_df_2021 = baseball_2021_df[["R", "BB+HBP",'2B', '3B', "HR", "SB", "CS"]]
runs_df_2021 = runs_df_2021.drop(runs_df_2021.index[-1])

# with sklearn 
regr = linear_model.LinearRegression()
regr.fit(runs_df_2021[[ "BB+HBP",'2B', '3B', "HR", "SB", "CS"]],runs_df_2021.R)

LinearRegression()

In [197]:
regr.coef_

array([0.31431862, 1.25107074, 1.67708315, 1.52209228, 0.5260915 ,
       0.07768891])

In [198]:
x = runs_df_2021.drop(columns=["R"])
y = runs_df_2021["R"]

r_squared = regr.score(x, y)
print(r_squared)

0.90263517212963

In [199]:
print(f"Intercept: {regr.intercept_} \n")
print(f"Coefficients: {regr.coef_}\n\n")

# This is the statistic model 

x = sm.add_constant(x) # adding a constant 
model = sm.OLS(y,x).fit()
predictions = model.predict(x)

print_model = model.summary()
print(f"This is the results for the runs predicted \n\n {print_model}")

Intercept: -161.53725232238037

Coefficients: [0.31431862 1.25107074 1.67708315 1.52209228 0.5260915  0.07768891]


This is the results for the runs predicted

                             OLS Regression Results
==============================================================================
Dep. Variable:                      R   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.878
Method:                 Least Squares   F-statistic:                     37.08
Date:                Wed, 04 Jan 2023   Prob (F-statistic):           5.47e-11
Time:                        15:16:24   Log-Likelihood:                -138.66
No. Observations:                  31   AIC:                             291.3
Df Residuals:                      24   BIC:                             301.4
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -161.5373     80.874     -1.997      0.057    -328.453       5.378
BB+HBP         0.3143      0.085      3.711      0.001       0.140       0.489
2B             1.2511      0.195      6.425      0.000       0.849       1.653
3B             1.6771      0.768      2.184      0.039       0.092       3.262
HR             1.5221      0.191      7.968      0.000       1.128       1.916
SB             0.5261      0.275      1.914      0.068      -0.041       1.093
CS             0.0777      0.774      0.100      0.921      -1.520       1.675
==============================================================================
Omnibus:                        6.214   Durbin-Watson:                   1.703
Prob(Omnibus):                  0.045   Jarque-Bera (JB):                4.544
Skew:                           0.745   Prob(JB):                        0.103
Kurtosis:                       4.140   Cond. No.                     1.29e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.29e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [200]:
# Import the Confusion Matrix 

X = runs_df_2021.drop(columns=["R"])
y = runs_df_2021["R"]

In [201]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# len(X_train)
# len(X_test)

X_train

    BB+HBP   2B  3B   HR   SB  CS
12     523  265  23  190   79  26
18     684  213  12  222   63  18
5      664  275  22  190   57  20
21     578  240  35  124   60  30
14     515  226  23  158  106  29
3      573  330  23  219   40  21
28     547  285  13  262   81  20
8      549  275  34  182   76  23
30     596  262  22  198   74  24
10     633  299  14  221   53  16
0      591  308  31  144   43  16
19     643  271  19  199   88  20
16     595  271  17  228   54  15
7      517  248  22  203  109  17
17     589  228  18  176   54  26
23     607  233  11  199   64  24
6      658  295  13  222   36  24
4      594  225  26  210   86  37
22     647  273  21  180  110  39
29     657  272  20  182   56  26
27     491  225  24  167  106  29
24     666  271  25  241   66  14
9      534  236  37  179   88  25
15     674  255  18  194   82  21

In [202]:
# Fit the Model (Logistic Regression)

model = LogisticRegression(solver='lbfgs', max_iter=1000000000)
model.fit(X_train,y_train)

/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(max_iter=1000000000)

In [203]:
#Make Predictions of The Logistic Regression Model and Make DataFrame between actual and predicted results
y_pred = model.predict(X_test)
results = pd.DataFrame({"Predicted":y_pred, "Actual":y_test}).reset_index(drop=True)
results

   Predicted  Actual
0        804     830
1        729     790
2        625     686
3        723     659
4        743     734
5        729     857
6        717     706

In [204]:
# Accuracy Score (Logistic Regression)
# from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# score_one = accuracy_score(y_pred, y_test)
# print(f"The Score For Logistic Regression: {score_one}")

In [205]:
# Make Predictions for the Linear Regression Model and Dataframe comparing actual and predicted values 
model2 = LinearRegression()
model2.fit(X_train, y_train)
y_pred = model2.predict(X_test)
results = pd.DataFrame({"Predicted":y_pred, "Actual":y_test}).reset_index(drop=True)
results

    Predicted  Actual
0  796.104713     830
1  798.102981     790
2  666.713681     686
3  702.242475     659
4  744.465221     734
5  829.520013     857
6  730.681662     706

In [210]:
# # Accuracy Score (Linear Regression)
# from sklearn.metrics import accuracy_score
# print(f"The Accuracy For Linear Regression :{accuracy_score(y_test, y_pred)}")

# Here are Linear and Logistic Regressions for 2022 Baseball Total Runs

In [ ]:
# Here, we will do linear regrerssion for perdicted runs for the seasons in 20201 and 2022
# The regression coefficients are 
# 
# First, here is 2021. 

runs_df_2022 = baseball_2022_df[["R", "BB+HBP",'2B', '3B', "HR", "SB", "CS"]]
runs_df_2022 = runs_df_2022.drop(runs_df_2022.index[-1])

# with sklearn 
regr = linear_model.LinearRegression()
regr.fit(runs_df_2022[[ "BB+HBP",'2B', '3B', "HR", "SB", "CS"]],runs_df_2022.R)

LinearRegression()

In [ ]:
print(f"Intercept: {regr.intercept_} \n")
print(f"Coefficients: {regr.coef_}\n\n")

# This is the statistic model 
x = sm.add_constant(x) # adding a constant 
model = sm.OLS(y,x).fit()
predictions = model.predict(x)

print_model = model.summary()
print(f"This is the results for the runs predicted \n\n {print_model}")

Intercept: 40.56521052018559

Coefficients: [ 0.21751824  1.09918506  1.10167132  1.33242044  0.05868437 -0.7474012 ]


This is the results for the runs predicted

                             OLS Regression Results
==============================================================================
Dep. Variable:                      R   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.878
Method:                 Least Squares   F-statistic:                     37.08
Date:                Wed, 04 Jan 2023   Prob (F-statistic):           5.47e-11
Time:                        14:19:30   Log-Likelihood:                -138.66
No. Observations:                  31   AIC:                             291.3
Df Residuals:                      24   BIC:                             301.4
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -161.5373     80.874     -1.997      0.057    -328.453       5.378
BB+HBP         0.3143      0.085      3.711      0.001       0.140       0.489
2B             1.2511      0.195      6.425      0.000       0.849       1.653
3B             1.6771      0.768      2.184      0.039       0.092       3.262
HR             1.5221      0.191      7.968      0.000       1.128       1.916
SB             0.5261      0.275      1.914      0.068      -0.041       1.093
CS             0.0777      0.774      0.100      0.921      -1.520       1.675
==============================================================================
Omnibus:                        6.214   Durbin-Watson:                   1.703
Prob(Omnibus):                  0.045   Jarque-Bera (JB):                4.544
Skew:                           0.745   Prob(JB):                        0.103
Kurtosis:                       4.140   Cond. No.                     1.29e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.29e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
regr.coef_

array([ 0.21751824,  1.09918506,  1.10167132,  1.33242044,  0.05868437,
       -0.7474012 ])

In [ ]:
x = runs_df_2022.drop(columns=["R"])
y = runs_df_2022["R"]

r_squared = regr.score(x, y)
print(r_squared)

0.8464476956290287

In [ ]:
# Import the Confusion Matrix 
X = runs_df_2022.drop(columns=["R"])
y = runs_df_2022["R"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# Fit the Model (Logistic Regression)
model = LogisticRegression(solver='lbfgs', max_iter=1000000000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000000000)

In [ ]:
#Make Predictions of The Logistic Regression Model and Make DataFrame between actual and predicted results
y_pred = model.predict(X_test)
results = pd.DataFrame({"Predicted":y_pred, "Actual":y_test}).reset_index(drop=True)
results

   Predicted  Actual
0        698     666
1        623     747
2        694     737
3        698     735
4        568     603
5        772     847
6        674     775

In [ ]:
# Make Predictions for the Linear Regression Model and Dataframe comparing actual and predicted values 
model2 = LinearRegression()
model2.fit(X_train, y_train)
y_pred = model2.predict(X_test)
results = pd.DataFrame({"Predicted":y_pred, "Actual":y_test}).reset_index(drop=True)
results

    Predicted  Actual
0  681.633341     666
1  721.269950     747
2  774.858198     737
3  774.471492     735
4  614.465132     603
5  857.967370     847
6  766.707851     775

# Here are other models I have used for practice (Looking at Baseball Players)

In [275]:
import os 
import pandas as pd 
import numpy as np 
from pybaseball import batting_stats
from pybaseball import pitching_stats

In [276]:
START = 2021
END = 2022

batting = batting_stats(START,END,qual=200)
pitching = pitching_stats(START, END, qual=200)

In [218]:
# batting.to_csv("batting_records.csv")
# pitching.to_csv("pitching_records.csv")

In [277]:
batting = batting.groupby("IDfg", group_keys=False).filter(lambda x: x.shape[0] > 1)
pitching = pitching.groupby("IDfg", group_keys=False).filter(lambda x: x.shape[0] > 1)

In [278]:
batting

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
0,15640,2022,Aaron Judge,NYY,30,157,570,696,177,87,...,118.4,246,0.609,404,0.169,0.287,NaN,NaN,NaN,11.2
31,11493,2022,Manny Machado,SDP,29,150,578,644,172,102,...,112.4,219,0.490,447,0.126,0.243,NaN,NaN,NaN,6.6
33,9777,2022,Nolan Arenado,STL,31,148,557,620,163,90,...,111.4,190,0.389,489,0.155,0.241,NaN,NaN,NaN,7.2
4,9218,2022,Paul Goldschmidt,STL,34,151,561,651,178,102,...,112.3,200,0.469,426,0.196,0.295,NaN,NaN,NaN,8.0
18,5361,2022,Freddie Freeman,LAD,32,159,612,708,199,129,...,112.3,248,0.480,517,0.122,0.206,NaN,NaN,NaN,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
717,5913,2022,Leury Garcia,CHW,31,97,300,315,63,52,...,109.2,82,0.342,240,0.126,0.256,NaN,NaN,NaN,-1.1
696,10071,2022,Jonathan Villar,- - -,31,59,202,220,42,31,...,109.5,58,0.397,146,0.114,0.268,NaN,NaN,NaN,-0.7
572,11680,2022,Elias Diaz,COL,31,105,351,381,80,51,...,111.8,107,0.393,272,0.134,0.244,NaN,NaN,NaN,-1.5
612,1744,2022,Miguel Cabrera,DET,39,112,397,433,101,86,...,111.0,115,0.382,301,0.149,0.270,NaN,NaN,NaN,-1.4
716,12984,2021,Jackie Bradley Jr.,MIL,31,134,387,428,63,40,...,108.4,104,0.403,258,0.169,0.323,NaN,NaN,NaN,-0.7

In [279]:
pitching

,IDfg,Season,Name,Team,Age,W,L,WAR,ERA,G,...,LA,Barrels,Barrel%,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xERA
0,18684,2022,Sandy Alcantara,MIA,26,14,9,5.7,2.28,32,...,5.5,32,0.052,114.8,239,0.385,620,0.153,0.275,NaN
7,18684,2021,Sandy Alcantara,MIA,25,9,15,4.3,3.19,33,...,4.5,35,0.061,115.7,227,0.394,576,0.146,0.279,NaN

In [284]:
batting_players = batting[["Name", "AB","AVG","SLG","H", "1B", "2B", "3B", "HR", "BB", "HBP","SB","CS"]]
batting_players

,Name,AB,AVG,SLG,H,1B,2B,3B,HR,BB,HBP,SB,CS
0,Aaron Judge,570,0.311,0.686,177,87,28,0,62,111,6,16,3
31,Manny Machado,578,0.298,0.531,172,102,37,1,32,63,1,9,1
33,Nolan Arenado,557,0.293,0.533,163,90,42,1,30,52,7,5,3
4,Paul Goldschmidt,561,0.317,0.578,178,102,41,0,35,79,5,7,0
18,Freddie Freeman,612,0.325,0.511,199,129,47,2,21,84,5,13,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
717,Leury Garcia,300,0.210,0.267,63,52,8,0,3,7,3,2,0
696,Jonathan Villar,202,0.208,0.302,42,31,6,2,3,15,0,7,0
572,Elias Diaz,351,0.228,0.368,80,51,18,2,9,25,2,0,1
612,Miguel Cabrera,397,0.254,0.317,101,86,10,0,5,28,3,1,0
716,Jackie Bradley Jr.,387,0.163,0.261,63,40,14,3,6,28,10,7,1

In [285]:
batting_players.to_csv("batting_player_2021_to_2022.csv")

In [287]:
batting_players_from_2021_to_2022 = pd.read_csv("/Users/owner/Analysis_Projects/batting_player_2021_to_2022.csv")

batting_players_from_2021_to_2022

,Unnamed: 0,Name,AB,AVG,SLG,H,1B,2B,3B,HR,BB,HBP,SB,CS,Total_Bases,Runs_Created
0,0,Aaron Judge,570,0.311,0.686,177,87,28,0,62,111,6,16,3,391,167.327511
1,31,Manny Machado,578,0.298,0.531,172,102,37,1,32,63,1,9,1,307,112.853583
2,33,Nolan Arenado,557,0.293,0.533,163,90,42,1,30,52,7,5,3,297,107.035714
3,4,Paul Goldschmidt,561,0.317,0.578,178,102,41,0,35,79,5,7,0,324,131.609302
4,18,Freddie Freeman,612,0.325,0.511,199,129,47,2,21,84,5,13,3,313,128.593438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529,717,Leury Garcia,300,0.210,0.267,63,52,8,0,3,7,3,2,0,80,18.838710
530,696,Jonathan Villar,202,0.208,0.302,42,31,6,2,3,15,0,7,0,61,16.023041
531,572,Elias Diaz,351,0.228,0.368,80,51,18,2,9,25,2,0,1,129,36.515873
532,612,Miguel Cabrera,397,0.254,0.317,101,86,10,0,5,28,3,1,0,126,38.859813
533,716,Jackie Bradley Jr.,387,0.163,0.261,63,40,14,3,6,28,10,7,1,101,24.002353

In [283]:
# Linear Regression By Players

import pandas as pd 
import numpy as np
import statsmodels.api as sm

from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

from matplotlib import pyplot as plt

In [304]:
X = batting_players_from_2021_to_2022[["BB", "HBP", "1B", "2B", "3B", "HR", "SB", "CS"]]
y = batting_players_from_2021_to_2022["Runs_Created"]

model_player = LinearRegression()

In [305]:
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2)

In [306]:
model_player.fit(X_train, y_train)

print(f"Intercept: {model_player.intercept_} \n")
print(f"Coefficients: { model_player.coef_}\n\n")

Intercept: -9.435270172698225

Coefficients: [ 0.17553458  0.11721449  0.37056723  0.64807632  0.63550731  1.33686419
  0.01006519 -0.12114479]

In [307]:
y_pred = model_player.predict(X_test)
results = pd.DataFrame({"Predicted":y_pred, "Actual":y_test}).reset_index(drop=True)
results

      Predicted      Actual
0    102.928608  112.041451
1     56.701617   51.309091
2     69.159474   63.582090
3    103.818271  104.228347
4     38.345151   34.927273
..          ...         ...
102   31.706363   35.520000
103   48.471711   47.437500
104   33.935392   35.077399
105   58.856269   51.428571
106   51.675924   56.350348

[107 rows x 2 columns]

In [308]:
# Naive Bayes 
batting_players_from_2021_to_2022

,Unnamed: 0,Name,AB,AVG,SLG,H,1B,2B,3B,HR,BB,HBP,SB,CS,Total_Bases,Runs_Created
0,0,Aaron Judge,570,0.311,0.686,177,87,28,0,62,111,6,16,3,391,167.327511
1,31,Manny Machado,578,0.298,0.531,172,102,37,1,32,63,1,9,1,307,112.853583
2,33,Nolan Arenado,557,0.293,0.533,163,90,42,1,30,52,7,5,3,297,107.035714
3,4,Paul Goldschmidt,561,0.317,0.578,178,102,41,0,35,79,5,7,0,324,131.609302
4,18,Freddie Freeman,612,0.325,0.511,199,129,47,2,21,84,5,13,3,313,128.593438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529,717,Leury Garcia,300,0.210,0.267,63,52,8,0,3,7,3,2,0,80,18.838710
530,696,Jonathan Villar,202,0.208,0.302,42,31,6,2,3,15,0,7,0,61,16.023041
531,572,Elias Diaz,351,0.228,0.368,80,51,18,2,9,25,2,0,1,129,36.515873
532,612,Miguel Cabrera,397,0.254,0.317,101,86,10,0,5,28,3,1,0,126,38.859813
533,716,Jackie Bradley Jr.,387,0.163,0.261,63,40,14,3,6,28,10,7,1,101,24.002353

In [318]:
# Naive Bayes Batting Average, Slugging Percentages vs. Runs Created

X = batting_players_from_2021_to_2022[["AVG", "SLG"]]
y = batting_players_from_2021_to_2022["Runs_Created"].astype("double")

X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2)

In [319]:
from sklearn.naive_bayes import GaussianNB

model_player_two = GaussianNB()

In [320]:
model_player_two.fit(X_train, y_train)

ValueError: Unknown label type: (array([ 13.01010101,  14.38308458,  14.80851064,  15.18811881,
        15.6       ,  16.02304147,  17.23913043,  17.74461538,
        18.01327434,  18.50185874,  18.57142857,  18.83870968,
        19.22916667,  19.32692308,  19.42201835,  19.42857143,
        20.63839286,  20.80465116,  21.19069767,  21.44059406,
        21.49812734,  21.49837134,  21.95319149,  22.12440191,
        22.83568075,  22.88059701,  22.98932384,  23.13442623,
        23.15942029,  23.40136054,  23.90322581,  23.90495868,
        24.00235294,  24.85714286,  25.91489362,  26.01470588,
        26.12794613,  26.55172414,  26.69767442,  26.70445344,
        27.07774799,  27.09310345,  27.33152174,  27.8490566 ,
        28.01204819,  28.04198473,  28.20664207,  28.57575758,
        28.60465116,  28.70431894,  28.84982935,  29.04861111,
        29.11764706,  29.1547619 ,  29.16107383,  29.66666667,
        29.69028871,  29.78971963,  30.10943396,  30.1689008 ,
        30.19312169,  30.22966507,  30.28571429,  30.41284404,
        30.48547718,  30.56941176,  30.70212766,  30.76527331,
        31.40816327,  31.5625    ,  31.82509506,  31.96485623,
        31.97368421,  32.30769231,  32.625     ,  33.07420495,
        33.25      ,  33.30722892,  33.49253731,  33.5243553 ,
        33.7810219 ,  33.78983051,  34.        ,  34.17      ,
        34.92727273,  35.04081633,  35.07739938,  35.14669927,
        35.36842105,  35.52      ,  35.57538462,  35.61212121,
        35.66666667,  35.76666667,  35.86432161,  36.08013937,
        36.44764398,  36.49337748,  36.51587302,  36.696     ,
        36.83934426,  36.93181818,  36.97897898,  37.1503268 ,
        37.18032787,  37.30673317,  37.33681462,  37.3715415 ,
        37.38970588,  37.46181818,  37.46594005,  37.51898734,
        37.67711599,  37.9787234 ,  38.08287293,  38.15261044,
        38.23728814,  38.32946636,  38.33505155,  38.62655602,
        38.85981308,  39.23076923,  39.24528302,  39.3325062 ,
        39.40809969,  39.49044586,  39.54423592,  39.615     ,
        39.84234234,  40.23746702,  40.89350649,  41.11170213,
        41.38658147,  41.48044693,  42.19428571,  42.22222222,
        42.5161987 ,  42.81016949,  43.05882353,  43.16224189,
        43.21272366,  43.37104072,  43.43220339,  43.48017621,
        43.53823529,  43.86290323,  43.91489362,  43.9683908 ,
        44.41310541,  44.4144385 ,  44.47630332,  44.76683938,
        44.78846154,  45.0944206 ,  45.30944625,  45.43250689,
        45.51543943,  45.66744731,  45.69762419,  45.89800443,
        46.13989637,  46.23350254,  46.30343008,  46.43294118,
        46.59866962,  47.04494382,  47.4375    ,  47.44897959,
        47.6119403 ,  47.62075848,  47.76334107,  48.06366048,
        48.21917808,  48.35214447,  48.36263736,  48.45535714,
        48.5645933 ,  48.65671642,  48.7972973 ,  49.16309013,
        49.28658537,  49.70454545,  49.94683027,  50.03225806,
        50.12737643,  50.14913958,  50.36879433,  50.51243781,
        50.80049261,  50.80831409,  50.86056645,  51.42857143,
        51.50095969,  51.5625    ,  51.84      ,  52.18181818,
        52.37274549,  52.47588424,  52.60294118,  52.71212121,
        52.88544892,  52.90434783,  53.003861  ,  53.07936508,
        53.27807487,  53.34224599,  53.35051546,  53.61033797,
        53.85626283,  54.25735294,  54.29661017,  54.45669291,
        54.88172043,  54.96850394,  55.06265664,  55.06681034,
        55.4078341 ,  55.48608137,  55.55228758,  55.68888889,
        55.94646272,  56.        ,  56.65756303,  56.6746988 ,
        56.94791667,  57.18819188,  58.205074  ,  58.28512397,
        58.43713733,  58.55294118,  58.56896552,  58.58823529,
        58.66974596,  59.22719141,  59.27246377,  59.42857143,
        59.55704698,  59.64772727,  59.73799127,  59.88700565,
        59.93220339,  60.04183267,  60.26521739,  60.31456311,
        60.46808511,  60.7787234 ,  60.896     ,  60.90630324,
        61.07734807,  61.08687616,  61.52654867,  61.69376694,
        61.97077244,  61.97247706,  62.25659051,  62.32931727,
        62.37410072,  62.40933573,  62.42653061,  62.4990689 ,
        62.58896797,  63.13754647,  63.42857143,  63.58208955,
        64.02234637,  64.18164436,  64.60695652,  64.64516129,
        64.7373913 ,  64.73779385,  65.08589951,  65.22508591,
        65.30827068,  65.51126516,  65.62305987,  66.10084034,
        66.875     ,  67.14723926,  67.72202166,  67.95373665,
        68.0126183 ,  68.09622642,  68.29151292,  68.42091153,
        68.66666667,  68.73933649,  69.04727273,  69.13378685,
        69.31262136,  69.42857143,  70.28639618,  70.546875  ,
        70.61538462,  70.8       ,  70.87636364,  71.09719222,
        71.17826825,  71.2173913 ,  71.43502825,  71.62671233,
        71.88037383,  71.89393939,  72.46560847,  72.76717557,
        72.81678082,  72.96551724,  73.51102941,  73.57142857,
        73.85387324,  73.91102515,  74.39842209,  74.66505636,
        74.91946309,  75.03821656,  75.04868914,  75.33333333,
        75.5062167 ,  75.54455446,  75.55860806,  75.59369527,
        75.95252226,  76.03883495,  76.56122449,  76.71122112,
        76.75328467,  76.816609  ,  76.90044577,  77.47102804,
        77.70934256,  78.43902439,  78.51957295,  79.        ,
        80.43087971,  80.65015015,  80.6732852 ,  81.27806563,
        81.40766551,  81.42474916,  81.84514003,  82.11018364,
        82.23220339,  82.24474187,  82.36721311,  82.63539823,
        83.00353357,  83.07360862,  83.27149321,  83.39903846,
        83.47735192,  83.52073733,  83.53090909,  84.13577982,
        84.37288136,  84.97674419,  85.09247649,  85.35454545,
        85.51277955,  85.64696734,  86.09271523,  86.17021277,
        86.60130719,  86.63333333,  86.63736264,  86.63747811,
        86.80511182,  86.8907563 ,  87.33543307,  87.89189189,
        89.20253165,  89.93856655,  90.93853073,  91.53630363,
        91.82424242,  92.31958763,  92.37699681,  92.57271364,
        93.60243056,  94.00552486,  94.23688156,  94.26397516,
        95.08597285,  95.27410208,  95.85160202,  96.02589928,
        96.30486009,  96.5015674 ,  96.642978  ,  96.76251788,
        96.81355932,  96.87820513,  96.95461201,  97.65604027,
        99.1512605 ,  99.28391167, 100.6777251 , 102.0385185 ,
       102.1467626 , 102.225     , 103.8136943 , 103.8420268 ,
       104.1794872 , 104.2283465 , 105.0971429 , 106.3740095 ,
       107.0357143 , 107.065053  , 107.0991254 , 109.0447761 ,
       110.1612426 , 112.0414508 , 112.3630573 , 112.7454545 ,
       112.8609865 , 114.0652819 , 114.1509434 , 114.6168224 ,
       116.2981651 , 117.8113731 , 118.5270758 , 118.8131868 ,
       118.969697  , 120.2461059 , 125.5346687 , 128.5934379 ,
       131.6093023 , 167.3275109 ]),)

In [228]:
# batting_players = pd.read_csv("/Users/owner/Analysis_Projects/batting_players.csv")

# batting_players

,Unnamed: 0,Name,AB,AVG,SLG,H,1B,2B,3B,HR,BB,HBP,TB,Runs Created
0,0,Barry Bonds,403,0.370,0.799,149,70,31,2,46,198,9,322,187.921312
1,1,Barry Bonds,373,0.362,0.812,135,60,27,3,45,232,9,303,185.550489
2,8,Aaron Judge,570,0.311,0.686,177,87,28,0,62,111,6,391,167.327511
3,15,Mookie Betts,520,0.346,0.640,180,96,47,5,32,81,8,333,147.088670
4,2,Barry Bonds,390,0.341,0.749,133,65,22,1,45,148,10,292,155.058394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6749,6885,Gerald Laird,270,0.207,0.304,56,40,11,0,5,18,3,82,21.697595
6750,7042,Chris Davis,470,0.168,0.296,79,51,12,0,16,41,7,139,34.079151
6751,6673,Adam Dunn,415,0.159,0.277,66,39,16,0,11,75,4,115,33.755061
6752,6988,Neifi Perez,554,0.236,0.303,131,104,20,4,3,20,0,168,44.195122
6753,978,Ryan Doumit,431,0.318,0.501,137,88,34,0,15,23,6,216,77.947826

In [255]:
# SVD Algorithm 
from sklearn.svm import SVC 
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn import preprocessing
from sklearn import utils

model = SVC()
second_model = GaussianNB()
third_model = LogisticRegression(max_iter=1000)
forth_model = LinearRegression()

X = batting_players[["H", "1B", "2B","3B", "HR", "BB", "HBP","TB"]]
y = batting_players["Runs Created"]

In [257]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=20)

In [258]:
lab = preprocessing.LabelEncoder()
y_transformed = lab.fit_transform(y_train)

# Fit The SVD Model
third_model.fit(X_train, y_transformed)

/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(max_iter=1000)

In [260]:
y_pred = third_model.predict(X_test)

results = pd.DataFrame({"Predicted":y_pred, "Actual":y_test}).reset_index(drop=True)
results

    Predicted      Actual
0        5815   80.976816
1        6472   71.478873
2        5435   64.982517
3        4772   38.755501
4        2429   36.428571
5        1147   20.977778
6        3810   63.582090
7        5904   74.515108
8        4773  101.549296
9        4797   68.248739
10       5665   80.703297
11       6518   90.328455
12       3598   57.452830
13       1204   28.212560
14       3792   31.057252
15       6578   85.407643
16       4168   80.737864
17         63   17.908163
18       4152   57.889447
19       1092   34.057395