In [152]:
import pandas as pd 
import numpy as np
import statsmodels.api as sm

from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

from matplotlib import pyplot as plt

In [153]:
file_path = "/Users/owner/Analysis_Projects/sportsref_download_2021.csv"
file_path_two = "/Users/owner/Analysis_Projects/sportsref_download_2022.csv"

baseball_2021_df = pd.read_csv(file_path)
baseball_2022_df = pd.read_csv(file_path_two)

baseball_2021_df

,Tm,#Bat,BatAge,R/G,G,PA,AB,R,H,2B,...,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,LOB,BB+HBP
0,Arizona Diamondbacks,64,28.9,4.19,162,6144,5489,679,1297,308,...,0.692,87,2099,99,54,32,28,24,1152,591
1,Atlanta Braves,56,28.2,4.91,161,6056,5363,790,1307,269,...,0.754,98,2333,81,67,32,43,36,1072,616
2,Baltimore Orioles,62,26.7,4.07,162,5983,5420,659,1296,266,...,0.705,92,2177,105,65,14,31,12,1046,516
3,Boston Red Sox,56,28.0,5.12,162,6122,5495,829,1434,330,...,0.777,106,2467,100,61,10,42,22,1093,573
4,Chicago Cubs,69,29.1,4.35,162,5972,5306,705,1255,225,...,0.719,93,2162,133,92,40,30,17,1019,594
5,Chicago White Sox,47,28.0,4.91,162,6084,5357,796,1373,275,...,0.758,106,2262,139,78,24,39,10,1125,664
6,Cincinnati Reds,55,28.9,4.85,162,6162,5423,786,1352,295,...,0.759,95,2339,129,105,35,45,22,1110,658
7,Cleveland Indians,48,26.7,4.43,162,5907,5332,717,1269,248,...,0.710,94,2170,105,64,20,36,18,987,517
8,Colorado Rockies,45,28.1,4.59,161,6007,5374,739,1338,275,...,0.731,86,2227,98,58,48,36,24,1074,549
9,Detroit Tigers,49,28.1,4.30,162,5979,5376,697,1299,236,...,0.707,96,2146,113,44,17,50,8,1031,534
10,Houston Astros,52,28.9,5.33,162,6291,5593,863,1496,299,...,0.783,113,2486,136,64,9,54,25,1159,633
11,Kansas City Royals,48,29.3,4.23,162,5993,5427,686,1349,251,...,0.702,90,2147,100,55,31,52,8,1050,476
12,Los Angeles Angels,64,29.2,4.46,162,6016,5437,723,1331,265,...,0.717,93,2212,107,59,30,25,35,1029,523
13,Los Angeles Dodgers,61,29.2,5.12,162,6239,5445,830,1330,247,...,0.759,101,2336,96,104,32,45,36,1169,717
14,Miami Marlins,61,28.2,3.85,162,5929,5348,623,1244,226,...,0.671,81,1990,95,65,30,30,25,1042,515
15,Milwaukee Brewers,61,28.7,4.56,162,6099,5362,738,1251,255,...,0.713,92,2124,102,88,25,35,26,1113,674
16,Minnesota Twins,57,28.3,4.50,162,6078,5431,729,1311,271,...,0.738,103,2300,122,70,7,42,17,1092,595
17,New York Mets,64,28.2,3.93,162,5856,5210,636,1243,228,...,0.705,93,2035,123,94,34,23,25,1099,589
18,New York Yankees,59,29.3,4.39,162,6060,5331,711,1266,213,...,0.729,100,2169,154,63,10,34,14,1097,684
19,Oakland Athletics,50,30.1,4.59,162,6104,5395,743,1284,271,...,0.723,102,2190,99,98,17,49,17,1084,643
20,Philadelphia Phillies,55,29.1,4.53,162,6089,5366,734,1288,262,...,0.726,95,2192,103,67,47,43,37,1115,631
21,Pittsburgh Pirates,64,27.5,3.76,162,5983,5336,609,1261,240,...,0.673,82,1943,102,49,31,37,24,1128,578
22,San Diego Padres,54,28.0,4.50,162,6119,5384,729,1305,273,...,0.722,101,2160,121,61,36,46,42,1123,647
23,Seattle Mariners,63,27.0,4.30,162,6010,5355,697,1209,233,...,0.688,92,2061,92,72,9,36,8,1040,607
24,San Francisco Giants,54,30.6,4.96,162,6196,5462,804,1360,271,...,0.769,107,2404,117,64,36,30,45,1138,666
25,St. Louis Cardinals,51,28.5,4.36,162,6001,5351,706,1303,261,...,0.725,99,2202,99,86,40,44,32,1081,564
26,Tampa Bay Rays,61,27.7,5.29,162,6213,5507,857,1336,288,...,0.750,110,2362,75,72,6,41,27,1085,657
27,Texas Rangers,54,26.8,3.86,162,5943,5405,625,1254,225,...,0.670,83,2028,113,58,16,31,10,1007,491
28,Toronto Blue Jays,62,26.8,5.22,162,6070,5476,846,1455,285,...,0.797,113,2552,112,51,10,35,14,1056,547
29,Washington Nationals,60,28.7,4.47,162,6113,5385,724,1388,272,...,0.754,107,2246,158,84,38,31,43,1185,657
30,League Average,50,28.4,4.53,162,6061,5398,734,1316,262,...,0.728,97,2217,111,70,26,38,23,1087,596
31,NaN,1508,28.4,4.53,4858,181818,161941,22010,39484,7863,...,0.728,97,66521,3328,2112,766,1143,703,32601,17906

In [154]:
baseball_2022_df

,Tm,#Bat,BatAge,R/G,G,PA,AB,R,H,2B,...,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,LOB,BB+HBP
0,Arizona Diamondbacks,57,26.5,4.33,162,6027,5351,702,1232,262,...,0.689,95,2061,97,60,31,50,14,1039,591
1,Atlanta Braves,53,27.5,4.87,162,6082,5509,789,1394,298,...,0.761,111,2443,103,66,1,36,13,1030,536
2,Baltimore Orioles,58,27.0,4.16,162,6049,5429,674,1281,275,...,0.695,97,2119,95,83,12,43,10,1095,559
3,Boston Red Sox,54,28.8,4.54,162,6144,5539,735,1427,352,...,0.731,102,2268,131,63,12,50,23,1133,541
4,Chicago Cubs,64,27.9,4.06,162,6072,5425,657,1293,265,...,0.698,96,2097,130,84,19,36,16,1100,591
5,Chicago White Sox,44,29.3,4.23,162,6123,5611,686,1435,272,...,0.698,97,2172,127,73,16,35,9,1117,461
6,Cincinnati Reds,66,29.4,4.00,162,5978,5380,648,1264,235,...,0.676,83,2003,127,92,12,33,6,1020,544
7,Cleveland Guardians,50,25.9,4.31,162,6163,5558,698,1410,273,...,0.699,102,2126,115,81,22,52,36,1156,531
8,Colorado Rockies,43,29.1,4.31,162,6105,5540,698,1408,280,...,0.713,90,2203,139,61,10,40,10,1113,514
9,Detroit Tigers,53,27.9,3.44,162,5870,5378,557,1240,235,...,0.632,84,1859,108,58,10,44,8,1015,438
10,Houston Astros,45,29.3,4.55,162,6054,5409,737,1341,284,...,0.743,111,2293,118,60,9,42,18,1068,588
11,Kansas City Royals,55,27.1,3.95,162,6010,5437,640,1327,247,...,0.686,93,2064,101,48,20,44,7,1091,508
12,Los Angeles Angels,66,27.9,3.85,162,5977,5423,623,1265,219,...,0.687,94,2116,95,54,25,25,28,1050,503
13,Los Angeles Dodgers,51,29.6,5.23,162,6247,5526,847,1418,325,...,0.775,112,2441,85,56,3,53,22,1159,663
14,Miami Marlins,56,28.8,3.62,162,5949,5395,586,1241,248,...,0.658,86,1961,120,70,4,36,6,1045,506
15,Milwaukee Brewers,51,29.1,4.48,162,6122,5417,725,1271,251,...,0.724,105,2213,117,80,11,37,25,1102,657
16,Minnesota Twins,61,26.9,4.30,162,6113,5476,696,1356,269,...,0.718,107,2195,133,62,10,46,11,1126,580
17,New York Mets,61,29.7,4.77,162,6176,5489,772,1422,272,...,0.744,113,2261,122,112,20,44,25,1158,622
18,New York Yankees,54,30.2,4.98,162,6172,5422,807,1308,225,...,0.751,113,2311,121,70,14,41,36,1093,690
19,Oakland Athletics,64,28.3,3.51,162,5863,5314,568,1147,249,...,0.626,82,1837,109,59,22,33,7,969,492
20,Philadelphia Phillies,56,28.1,4.61,162,6077,5496,747,1392,255,...,0.739,107,2320,116,52,6,44,15,1075,530
21,Pittsburgh Pirates,68,26.3,3.65,162,5912,5331,591,1186,221,...,0.655,84,1939,96,54,19,32,14,1016,530
22,San Diego Padres,55,28.2,4.35,162,6175,5468,705,1317,275,...,0.700,104,2087,95,65,17,46,24,1174,639
23,Seattle Mariners,59,27.5,4.26,162,6117,5375,690,1236,229,...,0.704,106,2094,120,89,9,45,17,1129,685
24,San Francisco Giants,66,30.0,4.42,162,6117,5392,716,1261,255,...,0.705,98,2101,109,95,6,53,14,1115,666
25,St. Louis Cardinals,51,28.8,4.77,162,6165,5496,772,1386,290,...,0.745,114,2309,112,80,5,45,11,1132,617
26,Tampa Bay Rays,61,27.0,4.11,162,6008,5412,666,1294,296,...,0.686,100,2041,93,57,7,31,13,1074,557
27,Texas Rangers,55,28.0,4.36,162,6029,5478,707,1308,224,...,0.696,98,2166,82,47,10,38,12,1007,503
28,Toronto Blue Jays,51,27.1,4.78,162,6158,5555,775,1464,307,...,0.760,116,2395,136,55,8,33,13,1111,555
29,Washington Nationals,55,28.7,3.72,162,5998,5434,603,1351,252,...,0.688,99,2051,141,60,20,37,12,1099,502
30,League Average,50,28.2,4.28,162,6068,5449,694,1322,265,...,0.706,100,2152,113,68,13,41,16,1087,563
31,NaN,1495,28.2,4.28,4860,182052,163465,20817,39675,7940,...,0.706,100,64546,3393,2046,390,1224,475,32611,16899

# Here are Linear and Logistic Regressions for 2021 Baseball Total Runs

In [155]:
# Here, we will do linear regrerssion for perdicted runs for the seasons in 20201 and 2022
# The regression coefficients are 
# 
# First, here is 2021. 

runs_df_2021 = baseball_2021_df[["R", "BB+HBP",'2B', '3B', "HR", "SB", "CS"]]
runs_df_2021 = runs_df_2021.drop(runs_df_2021.index[-1])

# with sklearn 
regr = linear_model.LinearRegression()
regr.fit(runs_df_2021[[ "BB+HBP",'2B', '3B', "HR", "SB", "CS"]],runs_df_2021.R)

LinearRegression()

In [156]:
regr.coef_

array([0.31431862, 1.25107074, 1.67708315, 1.52209228, 0.5260915 ,
       0.07768891])

In [157]:
x = runs_df_2021.drop(columns=["R"])
y = runs_df_2021["R"]

r_squared = regr.score(x, y)
print(r_squared)

0.90263517212963

In [158]:
print(f"Intercept: {regr.intercept_} \n")
print(f"Coefficients: {regr.coef_}\n\n")

# This is the statistic model 

x = sm.add_constant(x) # adding a constant 
model = sm.OLS(y,x).fit()
predictions = model.predict(x)

print_model = model.summary()
print(f"This is the results for the runs predicted \n\n {print_model}")

Intercept: -161.53725232238037

Coefficients: [0.31431862 1.25107074 1.67708315 1.52209228 0.5260915  0.07768891]


This is the results for the runs predicted

                             OLS Regression Results
==============================================================================
Dep. Variable:                      R   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.878
Method:                 Least Squares   F-statistic:                     37.08
Date:                Wed, 04 Jan 2023   Prob (F-statistic):           5.47e-11
Time:                        13:59:16   Log-Likelihood:                -138.66
No. Observations:                  31   AIC:                             291.3
Df Residuals:                      24   BIC:                             301.4
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -161.5373     80.874     -1.997      0.057    -328.453       5.378
BB+HBP         0.3143      0.085      3.711      0.001       0.140       0.489
2B             1.2511      0.195      6.425      0.000       0.849       1.653
3B             1.6771      0.768      2.184      0.039       0.092       3.262
HR             1.5221      0.191      7.968      0.000       1.128       1.916
SB             0.5261      0.275      1.914      0.068      -0.041       1.093
CS             0.0777      0.774      0.100      0.921      -1.520       1.675
==============================================================================
Omnibus:                        6.214   Durbin-Watson:                   1.703
Prob(Omnibus):                  0.045   Jarque-Bera (JB):                4.544
Skew:                           0.745   Prob(JB):                        0.103
Kurtosis:                       4.140   Cond. No.                     1.29e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.29e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [159]:
# Import the Confusion Matrix 

X = runs_df_2021.drop(columns=["R"])
y = runs_df_2021["R"]

In [171]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# len(X_train)
# len(X_test)

X_train

    BB+HBP   2B  3B   HR   SB  CS
12     523  265  23  190   79  26
2      516  266  15  195   54  23
28     547  285  13  262   81  20
14     515  226  23  158  106  29
19     643  271  19  199   88  20
9      534  236  37  179   88  25
27     491  225  24  167  106  29
8      549  275  34  182   76  23
15     674  255  18  194   82  21
30     596  262  22  198   74  24
6      658  295  13  222   36  24
24     666  271  25  241   66  14
22     647  273  21  180  110  39
0      591  308  31  144   43  16
7      517  248  22  203  109  17
16     595  271  17  228   54  15
13     717  247  24  237   65  17
23     607  233  11  199   64  24
1      616  269  20  239   59  19
5      664  275  22  190   57  20
18     684  213  12  222   63  18
20     631  262  24  198   77  19
25     564  261  22  198   89  22
29     657  272  20  182   56  26

In [172]:
# Fit the Model (Logistic Regression)

model = LogisticRegression(solver='lbfgs', max_iter=1000000000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000000000)

In [173]:
#Make Predictions of The Logistic Regression Model and Make DataFrame between actual and predicted results
y_pred = model.predict(X_test)
results = pd.DataFrame({"Predicted":y_pred, "Actual":y_test}).reset_index(drop=True)
results

   Predicted  Actual
0        659     829
1        625     686
2        729     863
3        697     705
4        724     609
5        729     857
6        697     636

In [175]:
# Accuracy Score (Logistic Regression)
score_one = model.score(X_test, y_test)
print(f"The Score For Logistic Regression: {score_one}")

The Score For Logistic Regression: 0.0

In [164]:
# Make Predictions for the Linear Regression Model and Dataframe comparing actual and predicted values 
model2 = LinearRegression()
model2.fit(X_train, y_train)
y_pred = model2.predict(X_test)
results = pd.DataFrame({"Predicted":y_pred, "Actual":y_test}).reset_index(drop=True)
results

    Predicted  Actual
0  740.905449     796
1  789.053381     863
2  601.458801     609
3  695.320411     679
4  833.719350     804
5  798.664286     790
6  633.218604     636

In [176]:
# Accuracy Score (Linear Regression)
from sklearn.metrics import accuracy_score
print(f"The Accuracy For Linear Regression :{accuracy_score(y_test, y_pred)}")

The Accuracy For Linear Regression :0.0

# Here are Linear and Logistic Regressions for 2022 Baseball Total Runs

In [181]:
# Here, we will do linear regrerssion for perdicted runs for the seasons in 20201 and 2022
# The regression coefficients are 
# 
# First, here is 2021. 

runs_df_2022 = baseball_2022_df[["R", "BB+HBP",'2B', '3B', "HR", "SB", "CS"]]
runs_df_2022 = runs_df_2022.drop(runs_df_2022.index[-1])

# with sklearn 
regr = linear_model.LinearRegression()
regr.fit(runs_df_2022[[ "BB+HBP",'2B', '3B', "HR", "SB", "CS"]],runs_df_2022.R)

LinearRegression()

In [182]:
print(f"Intercept: {regr.intercept_} \n")
print(f"Coefficients: {regr.coef_}\n\n")

# This is the statistic model 
x = sm.add_constant(x) # adding a constant 
model = sm.OLS(y,x).fit()
predictions = model.predict(x)

print_model = model.summary()
print(f"This is the results for the runs predicted \n\n {print_model}")

Intercept: 40.56521052018559

Coefficients: [ 0.21751824  1.09918506  1.10167132  1.33242044  0.05868437 -0.7474012 ]


This is the results for the runs predicted

                             OLS Regression Results
==============================================================================
Dep. Variable:                      R   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.878
Method:                 Least Squares   F-statistic:                     37.08
Date:                Wed, 04 Jan 2023   Prob (F-statistic):           5.47e-11
Time:                        14:19:30   Log-Likelihood:                -138.66
No. Observations:                  31   AIC:                             291.3
Df Residuals:                      24   BIC:                             301.4
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -161.5373     80.874     -1.997      0.057    -328.453       5.378
BB+HBP         0.3143      0.085      3.711      0.001       0.140       0.489
2B             1.2511      0.195      6.425      0.000       0.849       1.653
3B             1.6771      0.768      2.184      0.039       0.092       3.262
HR             1.5221      0.191      7.968      0.000       1.128       1.916
SB             0.5261      0.275      1.914      0.068      -0.041       1.093
CS             0.0777      0.774      0.100      0.921      -1.520       1.675
==============================================================================
Omnibus:                        6.214   Durbin-Watson:                   1.703
Prob(Omnibus):                  0.045   Jarque-Bera (JB):                4.544
Skew:                           0.745   Prob(JB):                        0.103
Kurtosis:                       4.140   Cond. No.                     1.29e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.29e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [179]:
regr.coef_

array([ 0.21751824,  1.09918506,  1.10167132,  1.33242044,  0.05868437,
       -0.7474012 ])

In [180]:
x = runs_df_2021.drop(columns=["R"])
y = runs_df_2021["R"]

r_squared = regr.score(x, y)
print(r_squared)

0.8626869096888373

In [183]:
# Import the Confusion Matrix 
X = runs_df_2021.drop(columns=["R"])
y = runs_df_2021["R"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# Fit the Model (Logistic Regression)
model = LogisticRegression(solver='lbfgs', max_iter=1000000000)
model.fit(X_train,y_train)

In [ ]:
#Make Predictions of The Logistic Regression Model and Make DataFrame between actual and predicted results
y_pred = model.predict(X_test)
results = pd.DataFrame({"Predicted":y_pred, "Actual":y_test}).reset_index(drop=True)
results